Teslajoy fileview
Sage-Bionetworks/synAnnotationUtils pull request #27
Opened 2017-03-15 21:41 UTC by teslajoy

testing git workflow for making changes to code

2017-03-17 20:05 UTC, xindiguo approved these changes

2017-03-17 20:20 UTC, kdaily requested changes

2017-03-17 20:20 UTC, kdaily commented on synAnnotationUtils/update.py
> +	 Updates File entity Annotations
make this [PEP 257](https://www.python.org/dev/peps/pep-0257/) compliant, please!

2017-03-18 00:54 UTC, kdaily approved these changes
Hooray!

![awesome](https://media3.giphy.com/media/mXnO9IiWWarkI/giphy.gif)

2017-03-18 00:56 UTC, kdaily commented
![awesome](https://media3.giphy.com/media/mXnO9IiWWarkI/giphy.gif)

2017-03-20 22:07 UTC, merged